### ISSUE TITLE
Confidence Score

### ISSUE THREAD

**Issue by shreyasvinaya** [MolecularAI/aizynthfinder#165]
Hi, 
Is there any way we can get the confidence score of each step of the retrosynthesis?
Do i have to change something in the config file/ parameters that i'm passing in?

This is the code that i'm currently using:
```python
finder = AiZynthFinder(configfile=config_filename)
finder.stock.select("zinc")
finder.expansion_policy.select("uspto")
finder.filter_policy.select("uspto")
finder.target_smiles = smiles
finder.tree_search()
finder.build_routes()
stats = finder.extract_statistics()
status = stats['is_solved']
result_dict = finder.routes.dict_with_extra(include_metadata=True,
                                            include_scores=True)
```

This is my config file:
```yml
expansion:
  uspto:
    - aizynthfinder/models/uspto_model.onnx
    - aizynthfinder/models/uspto_templates.csv.gz
  ringbreaker:
    - aizynthfinder/models/uspto_ringbreaker_model.onnx
    - aizynthfinder/models/uspto_ringbreaker_templates.csv.gz
filter:
  uspto: aizynthfinder/models/uspto_filter_model.onnx
stock:
  zinc: aizynthfinder/models/zinc_stock.hdf5
```

Thanks in advance
